### ISSUE TITLE
Space around globe

### ISSUE THREAD

**Issue by nanoteilchen** [earthjs/earthjs#2]
Love the project, congrats!
When I set width and height, there is still much space on each side. May there be a way to set a padding? And the canvas is always centered. a "position: left"-option would be very nice :-)

**Comment by earthjs** [comment]
[adding margin + fix world3d](https://github.com/earthjs/earthjs/commit/a12c31d9988baf675da76150edb6649bd0776c27)

**Comment by earthjs** [comment]
https://github.com/earthjs/earthjs/commit/28c0f3c3c58c20611b4762e80b23f0bf861b74ef

**Comment by nanoteilchen** [comment]
Thank you very much, works fine!
