### ISSUE TITLE
Flight Lines issue

### ISSUE THREAD

**Issue by riaanvj** [earthjs/earthjs#4]
Hi,

I was going through the Flight Lines demo but there seems to be an issue on this page: https://earthjs.github.io/16-threejs-demo/3-small_arms_.html

When you slide the Year slide it generates the following JS error: Uncaught TypeError: tj.group is not a function (flightLineThreejs.js:395)

**Comment by earthjs** [comment]
Hi, Thank you for the bug report !  I'll investigate it.

**Comment by earthjs** [comment]
code is fixed: 
https://github.com/earthjs/earthjs/commit/e001a3ffb5fe3e2fa826282dab62c36e59dd444e#diff-1399f79b2b94f38292b1cf7b063ce00b 

you can try again,  almost all example  now use inertiaPlugin, replacing mousePlugin.
